export { default as Author } from './Author';
export { default as Categories } from './Categories';
export {default as CollectionsWidget} from './CollectionsWidget'; 
export { default as Comments } from './Comments';
export { default as CommentsForm } from './CommentsForm';
export {default as FeaturedCollections} from './FeaturedCollections';
export {default as featuredPosts} from './FeaturedPosts';
export {default as Loader } from './Loader';
export { default as PostCard } from './PostCard';
export { default as PostDetail } from './PostDetail';
export { default as PostWidget } from './PostWidget';
export {default as SlidingCollections } from './SlidingCollections';
